<!doctype html>
<html>
  <head>
    <title>Scalar API Reference - Booking API</title>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1" />
    <style>
      body {
        margin: 0;
      }
    </style>
  </head>
  <body>
    <!-- 
      We point data-url to the JSON generated by Scramble.
      Scramble automatically generates OpenAPI specs at /docs/api.json
    -->
    <script
      id="api-reference"
      data-url="{{ url('/docs/api.json') }}"
      data-theme="purple"
      data-layout="modern"
    ></script>
    <script src="https://cdn.jsdelivr.net/npm/@scalar/api-reference"></script>
  </body>
</html>
